
# app floating
for_window [class="Gview.exe"] floating enabled 
for_window [app_id="com.follow.clash"] floating enabled 
for_window [class="wechat"] floating enabled 
for_window [class="baidunetdisk"] floating enabled 
for_window [class="scrcpy"] floating enabled 
for_window [title="floating-terminal"] floating enable
for_window [title="VMD Main"] floating enable
for_window [title="VMD 2.0.0a8 OpenGL Display"] floating enable

no_focus [class="wechat"]
